// Lab 3 icecream.cpp 
// WRITE A COMMENT BRIEFLY DESCRIBING THE PROGRAM. 
// PUT YOUR NAME HERE.
// INCLUDE ANY NEEDED FILES HERE.
using namespace std;

int main()
{  
   // DEFINE NAMED CONSTANTS HERE TO HOLD THE PRICES OF THE 3 
   // SIZES OF ICE CREAM CONES. GIVE EACH ONE A DESCRIPTIVE
   // NAME AND AN APPROPRIATE DATA TYPE. 
   
   // DECLARE ALL NEEDED VARIABLES HERE. GIVE EACH ONE A DESCRIPTIVE
   // NAME AND AN APPROPRIATE DATA TYPE. 
   
   // WRITE STATEMENTS HERE TO PROMPT FOR AND INPUT THE INFORMATION
   // THE PROGRAM NEEDS TO GET FROM THE USER.
   
   // WRITE STATEMENTS HERE TO PERFORM ALL NEEDED COMPUTATIONS  
   // AND ASSIGN THE RESULTS TO VARIABLES.
   
   // WRITE STATEMENTS HERE TO DISPLAY THE REQUESTED INFORMATION.
      
   return 0;
}
